### ISSUE TITLE
Database contains sensitive information

### ISSUE THREAD

**Issue by tess-aaa** [Vanege/conlang-corpora#1]
When searching for the definition of 'sposida' in Elefen-to-English mode, the result is very sensitive information.

[https://conlang-corpora.vercel.app/?l1=Elefen&l2=English&selectedCorpusIds=%5B0%5D&search=](https://conlang-corpora.vercel.app/?l1=Elefen&l2=English&selectedCorpusIds=%5B0%5D&search=)

**Comment by LucasLarson** [comment]
Remarkably, what you found there appears to be an excerpt from Cory Doctorow’s 2008 [_Little Brother_](https://archive.org/details/ost-english-cory_doctorow_-_little_brother/page/n6/mode/1up).

**Comment by tess-aaa** [comment]
Grasias, me vide la sinia de sita aora.
(Thank you, I see the quote now.)
